### ISSUE TITLE
Shortcut for specified app

### ISSUE THREAD

**Issue by mbnoimi** [charlesmilette/Firefox.MarketplaceShortcut#1]
I'm not sure what if this is right place to ask my question but I wish to get a help from you.

Is there any way to add a shortcut for a specified app from Firefox Marketplace instead of all Firefox Marketplace (ex. [Telegram](https://marketplace.firefox.com/app/telegram?src=search))?

**Comment by charlesmilette** [comment]
You can by editing this line of code:
`tabs.open("https://marketplace.firefox.com/");` (Line 15 of file lib/main.js)
But if you want to open directly the app, it's impossible because the app works fully separated from Firefox and I don't know how to check if the app is intalled and to call it. You can still press the open button from the Firefox Marketplace to open it.
